### ISSUE TITLE
OpenVINO DevCon https://webinar.intel.com/OpenVINODevCon_reg

### ISSUE THREAD

**Issue by jmburris** [unicorncoding/devevents-web#106]
Intel is having a virtual developer conference called OpenVINO DevCon on June 13, 8:00am - 4:30pm PDT. Free to join. OpenVINO is Intel's open source AI inference toolkit for optimizing and deploying AI models into applications on Intel CPU, GPU, and VPUs...on PCs or servers/datacenters. Intel released 2022.1 with many new enhancements that will be explained. The event will have workshops and an AI challenge.  https://webinar.intel.com/OpenVINODevCon_reg

**Comment by unicorncoding** [comment]
https://dev.events/conferences/open-vino-dev-con-online-5-2022
