### ISSUE TITLE
 <Python at Scale> <https://www.pythonatscale.com/>

### ISSUE THREAD

**Issue by MartinaSardaryan** [unicorncoding/devevents-web#107]
The Python at Scale Summit is a venue to highlight innovative big data solutions for Python developers and enterprises. The Summit provides an opportunity for enterprises and organizations to understand common big data challenges, share their approaches to solving those challenges, and learn about innovative solutions that can help mature data-driven operations. Enterprises, vendors, and developer communities are welcome to showcase their solutions to large-scale data problems.

The summit will be held on October 27 and 28, 2022 at the Hilton in Austin, Texas and will feature some great speakers, including Dr. Katrina Riehl – Head of Data at Streamlit (Snowflake) and President NumFOCUS Board of Directors, Dr. Nicholas Sofroniew – Director, Product Management, Imaging at Chan Zuckerberg Initiative, Brian Granger – Co-creator of Project Jupyter and the Jupyter Notebook, Senior Principal Technologist at Amazon Web Services (AWS), and Matt Rocklin – Creator of Dask and CEO of Coiled and others.

Texas, Austin:
Oct 27, 2022 – Oct 28, 2022

Don’t miss out!

**Comment by unicorncoding** [comment]
https://dev.events/conferences/python-at-scale-summit-austin-9-2022
