### ISSUE TITLE
<Intellias Agile Days> <https://www.career-launch.intellias.com/intellias-agile-days>

### ISSUE THREAD

**Issue by UliiaS** [unicorncoding/devevents-web#108]
16 hours of speeches, 20 international speakers, and over 1000 participants from all over the world — don’t miss Intellias Agile Days! Agile principles help us in times of uncertainty. People around the world are now adapting to the new reality. And Agile can help with that.

What have we prepared for you?

🔹 Speeches from experts from Intellias, Tesla, Spotify, and other leading companies

🟡A space for sharing experiences and ideas

🔹Opportunity for exploring, innovating, and advancing Agile values and principles

Let's take a look at our agenda:

“From Agile to Versatile. Unfix Your Organization!” by Jurgen Appelo
“Agile at Tesla” by Joe Justice
“Adding Personal Coaching to your crisis dealing toolbox” by Nikola Bogdanov
“Make your Scrum Teams more user-centric and outcome-oriented” by Alex Ballarin
“How to run teams at scale remotely” by Oleksiy Shebanov
“Agility values for business and teams” by Alina Piddubna
“Product Management at Intellias” by Roman Pavlyuk, Ruslan Lagutin
“Efficiency and effectiveness of agile teams” by Iaroslav Bondarchuk
“The Clone Army — why is it a bad idea to create one in real life? And why are we still trying to do so?” by Kate Hobler
Find out more about the speakers and apply here: https://www.career-launch.intellias.com/intellias-agile-days

🔹 Participation is free, but we will be glad to receive your donations for any amount. Our goal is to raise funds for nonprofit organizations dedicated to providing humanitarian aid to the people of Ukraine.
![завантаження](https://user-images.githubusercontent.com/105912794/169811591-d40c54dd-804b-4bb5-ae84-bc33d0fcc99d.png)
[](url)

**Comment by unicorncoding** [comment]
https://dev.events/conferences/intellias-agile-days-online-5-2022
