### ISSUE TITLE
<I Code Java Africa> <www.j-sa.co>

### ISSUE THREAD

**Issue by Evenir1** [unicorncoding/devevents-web#110]
Africa’s Longest Running Java and Kotlin Conference. We host global speakers and Java Champions.
I Code Java Conference will be held 12 – 14th October 2022 in Johannesburg, South Africa. It’s our first hybrid summit for I Code Java. ICJ has always been a community driven event which focusses on coding, architecture and developing leadership skills. Developing a strong fundamental skillset to further your career. We extremely proud to announce 20% of our tickets are FREE to full-time students in Africa. We are advocates for developing our future programmers.

**Comment by unicorncoding** [comment]
https://dev.events/conferences/i-code-java-hybrid-johannesburg-9-2022
