### ISSUE TITLE
<NodeJs One Africa> <www.nodejsone.com>

### ISSUE THREAD

**Issue by Evenir1** [unicorncoding/devevents-web#111]
NodeJs One Africa will be hosting our inaugural Conference 7-9th September. This three-day conference will bring together local and international developers who share a common passion. Our goal is to highlight Africa’s amazing developer community with a view to learn, connect and share ideas. Our first event will be a Hybrid Edition, in-person with virtual access for those unable to attend. Day 1 will be 4 interactive workshop, Day 2 and 3 will see International speakers hosting 40 minute session. 

Full Time scholars will get free virtual access.

**Comment by unicorncoding** [comment]
the web site is under construction, and not all info is clear
