### ISSUE TITLE
Please add event wrocloverb https://wrocloverb.com/

### ISSUE THREAD

**Issue by mbronek7** [unicorncoding/devevents-web#113]
https://wrocloverb.com/

The main goal of the conference is to help Ruby professionals become better at what they do.

wroclove.rb serves best to people who are already fluent with Ruby. The ideas presented at our conference are very advanced. They are meant to inspire the way we write code, the way we help our clients and users. It’s not uncommon for us to present you ideas that come from the Java and .NET worlds, we believe that their ideas can have a great influence on our community. There are good  reasons, why our conference is called “the best Java conference in the Ruby world”.

**Comment by unicorncoding** [comment]
https://dev.events/conferences/wroclove-rb-wroclaw-8-2022

**Comment by mbronek7** [comment]
thank you!
