### ISSUE TITLE
<Global SRE Virtual Conference July 2022> <https://www.globalbigdataconference.com/santa-clara/global-sre-virtual-conference/event-131.html>

### ISSUE THREAD

**Issue by gbdconference** [unicorncoding/devevents-web#124]
Global Big Data Conference's vendor agnostic Global SRE(Site Reliability Engineering)  Virtual Conference is held on July 25 - 27 2022

Overview:  
https://www.globalbigdataconference.com/santa-clara/global-sre-virtual-conference/event-131.html

Register now
https://www.eventbrite.com/tickets-external?eid=335574621727&ref=etckt&v=2&discount=GAIC20

If you have any questions , please do not hesitate to contact [events@globalbigdataconference.com](mailto:events@globalbigdataconference.com) or Call: 408-400-3769

Thanks
Leena Hanson
VP

**Comment by unicorncoding** [comment]
https://dev.events/conferences/global-sre-virtual-conference-online-6-2022
