### ISSUE TITLE
Please add event React Brussels

### ISSUE THREAD

**Issue by sizovs** [unicorncoding/devevents-web#127]
Dear Eduards, 

I am Omar  from BeJS; The first Belgian JavaScript Community, We organize meetups, events and activities about JS & Co.  

The BeJS team is now preparing the 2nd edition of REACT BRUSSELS Conference (to happen next October 14th - Hybrid, and I am reaching out to you asking for a partnership. I would appreciate to see our REACT BRUSSELS listed next to other EU confs on  https://dev.events/EU

Please let me know if it's OK. What exactly would you need from me to share? and what would you ask for in exchange?   

Looking forward to it. 

Respectfully,

**Comment by unicorncoding** [comment]
https://dev.events/conferences/react-brussels-hybrid-brussels-9-2022
