### ISSUE TITLE
Heart of Scrum Conference

### ISSUE THREAD

**Issue by ScrumTrainingInsitute** [unicorncoding/devevents-web#129]
### WHAT IS IT?
The Heart of Scrum conference is a refreshing alternative for Scrum professionals. It is a mixture of lightning fast talks in the morning, hands-on workshops in the afternoon and a wide range of deep digging Masterclasses, all focused on getting to the Heart of Scrum.

### WHERE?
The conference will be hosted at Rosen College of Hospitality Management, ranked #1 in the nation for hospitality and tourism management.

### WHEN?
The main, 2-Day conference will be held on August 8 & August 9, 2022
The Master Classes will be held on August 10 & 11, 2022
WHY ATTEND?
Learn and get inspired by the biggest players on the field of scrum.

 [813-358-6035](tel:813-358-6035)
 [jeos12@gmail.com](mailto:jeos12@gmail.com?Subject=Heart%20of%20Scrum%20Conference)
 [heartofscrum.org/conference2022](https://heartofscrum.org/conference2022)

**Comment by unicorncoding** [comment]
https://dev.events/conferences/heart-of-scrum-orlando-7-2022
