### ISSUE TITLE
Please add event <NG-DE> <https://ng-de.org/>

### ISSUE THREAD

**Issue by korneevamg** [unicorncoding/devevents-web#133]
For the community, by the community: https://ng-de.org NG-DE is the community-driven Angular conference in Germany. It will take place in Berlin, 6 - 7 October 2022. The venue BOLLE FESTSÄLE is located next to the beautiful Spree river, close to Bellevue palace and Tiergarten.

**Comment by unicorncoding** [comment]
https://dev.events/conferences/ng-de-berlin-9-2022
