### ISSUE TITLE
Please add event <vuejs.de Conf><https://conf.vuejs.de/>

### ISSUE THREAD

**Issue by korneevamg** [unicorncoding/devevents-web#134]
For the community, by the community: https://conf.vuejs.de/ - vuejs.de Conf is the **first community-driven Vue conference in Germany**. It will take place in Berlin, 5 October 2022. The venue BOLLE FESTSÄLE is located next to the beautiful Spree river, close to Bellevue palace and Tiergarten.

**Comment by unicorncoding** [comment]
https://dev.events/conferences/vuejs-de-berlin-9-2022
