### ISSUE TITLE
<BIG DATA CONFERENCE EUROPE 2022> <https://bigdataconference.eu/>

### ISSUE THREAD

**Issue by DATAMINER12** [unicorncoding/devevents-web#136]
Big Data Conference Europe is a two-day conference with technical talks in the fields of Big Data, High Load, Data Science, Machine Learning and AI.
Conference brings together developers, IT professionals and users to share their experience, discuss best practices, describe use cases and business applications related to their successes.
The event is designed to educate, inform and inspire – organized by people who are passionate about Big Data and Data Exploration. We look forward to seeing you there!

**Comment by unicorncoding** [comment]
https://dev.events/conferences/big-data-conference-europe-online-10-2022
