### ISSUE TITLE
Please add event - MetaVSummit - https://www.metavsummit.com/

### ISSUE THREAD

**Issue by ammarali67** [unicorncoding/devevents-web#137]
Meet Hundreds of Dedicated Web 3.0 Engineers, Founders, CEOs and Investors.
More Than 100 Web 3.0 Organization's to Be Present.

Event Location & Timing: 08:00 AM to 05:00 PM GMT+4, Dubai, UAE.
Physical Conference: Sept 14-15 2022.

**Comment by unicorncoding** [comment]
https://dev.events/conferences/metavsummit-dubai-8-2022
