### ISSUE TITLE
DeveloperWeek Cloud 2022

### ISSUE THREAD

**Issue by savadevic** [unicorncoding/devevents-web#166]
DeveloperWeek Cloud 2022 | September 7 - 8, 13 - 14, 2022 | LIVE & Virtual for 2022

Join 3,500+ developers, engineers, software architects, and technical leaders at the premier international cloud conference.

Join us LIVE in-person Sept 7 - 8, 2022, and VIRTUAL globally online, Sept 13 - 14, 2022.

- Future of Cloud-Native Computing
- DevOps Summit
- AI & ML in the Cloud
- Microservices Architecture Deployment
- Containers & Kubernetes Lifecycle
- Full Stack Cloud Security
...with 100+ live sessions from technical speakers converging online to discover this year’s newest cloud computing innovations, products, and best practices.

Speakers include 90+ leaders from: Atlassian, Google, Microsoft, Oracle, Red Hat, Cisco, IBM, and more!

DeveloperWeek Global is produced and owned by DevNetwork, the world's developer event community organization -- and producer of leading conferences for the developer, engineering & IT industries.

**Comment by unicorncoding** [comment]
https://dev.events/conferences/developer-week-cloud-austin-8-2022
