### ISSUE TITLE
GTC 2022 | The Developer Conference for the Era of AI | NVIDIA

### ISSUE THREAD

**Issue by Tech2345688** [unicorncoding/devevents-web#178]
NVIDIA GTC is more than an AI conference for developers. It’s a global experience that brings together thousands of brilliant innovators, researchers, creators, thought leaders, and decision-makers who are shaping our world with the power of AI, computer graphics, data science, and more. Explore curated playlists on today’s hottest topics and more–on-demand.

**Comment by unicorncoding** [comment]
https://dev.events/conferences/nvidia-gtc-developer-conference-online-8-2022
