### ISSUE TITLE
Please update "NVIDIA GTC" Conference URL & Category

### ISSUE THREAD

**Issue by lindacaplinger** [unicorncoding/devevents-web#188]
RE: https://dev.events/conferences/nvidia-gtc-developer-conference-online-8-2022

Can you please update our conference URL to the full path? (including WWW and trailing "/")
CORRECT:
https://www.nvidia.com/gtc/ 

Can you please also change our category to "Tech Leadership"?

Thanks!

**Comment by unicorncoding** [comment]
https://dev.events/conferences/nvidia-gtc-conference-online-8-2022
