### ISSUE TITLE
Please add event <UbuCon Asia 2022> <https://2022.ubucon.asia>

### ISSUE THREAD

**Issue by sukso96100** [unicorncoding/devevents-web#218]
Cloud, DevOps, Hardware/IoT categories should be fine.

Dates and location: Nov 26-27, Seoul, South Korea
Website: https://2022.ubucon.asia

**Comment by unicorncoding** [comment]
thank you . 
https://dev.events/conferences/ubu-con-asia-seoul-10-2022
