### ISSUE TITLE
Suggest adding LICENSE

### ISSUE THREAD

**Issue by jerdog** [unicorncoding/devevents-web#22]
For those interested in maybe helping out by submitting issues, fixing bugs, etc., it would be helpful to know what LICENSE you intended for this.

**Comment by unicorncoding** [comment]
Thanks, @jerdog 

Done: https://github.com/unicorncoding/devevents-web/commit/059cf2f127aa2ecabd785635eceedcce97e00a30

**Comment by jerdog** [comment]
Awesome! Glad to help
