### ISSUE TITLE
Please add event <ElixirConfUY> <https://elixirconf.uy/>

### ISSUE THREAD

**Issue by smartinez87** [unicorncoding/devevents-web#226]
November 11-12, 2022
Montevideo, Uruguay or Online

The conference for the Elixir community in Uruguay

Thank you 🙏

**Comment by unicorncoding** [comment]
There is no conference program and tickets are not available.

**Comment by smartinez87** [comment]
hi @unicorncoding, tickets are now live for the conference. CFP closed yesterday, so program will be up soon as well.
Would you mind adding the event to the list now?

**Comment by unicorncoding** [comment]
@smartinez87 Done ) https://dev.events/conferences/elixir-conf-uy-montevideo-10-2022

**Comment by smartinez87** [comment]
thank you!
