### ISSUE TITLE
Infobip Shift 2023, https://shift.infobip.com/

### ISSUE THREAD

**Issue by radisicc** [unicorncoding/devevents-web#306]
Dear team, please add Infobip Shift 2023

It's a 2-day multistage hybrid conference dedicated to people passionate about software, continuing the tradition of delivering interactive, engaging, and exciting content. Expect multiple tracks, learn from extraordinary minds, engage in in-person and virtual experiences, prospect from exhibit hall, and expand your network on afterparties. Everything brought to you by Infobip Shift.

Speakers https://shift.infobip.com/speakers/ 
CFP 2023 https://sessionize.com/infobip-shift-2023/

**_Date_**
Sep 18-19 2023
**_Location_**
Zadar, Croatia

**_Tags_**
Main Tag **Full-Stack**

**_Other Tags_**

.NET, Agile, Blockchain, Career, Cloud, DevOps, Fintech, JavaScript, Java, PHP, React, Python, QA/Testing, Product/UX, Full-stack,

**Comment by unicorncoding** [comment]
Done ) https://dev.events/conferences/infobip-shift-zadar-8-2023
