### ISSUE TITLE
Can I modify the event submitted

### ISSUE THREAD

**Issue by RichardCYC** [unicorncoding/devevents-web#36]
Hi Julia @unicorncoding,
thanks for creating such an awesome website to share good events.

I just uploaded my event but I found I typed in the wrong event information. Is that possible to modify the information?

The event link is: https://dev.events/conferences/work-with-engineering-lead-to-grow-career-online-2-2022
What I want to modify: change the link from [codementor.io/events/how-to-work-with-your-engineering-lead-dz0h527vtx](https://codementor.io/events/how-to-work-with-your-engineering-lead-dz0h527vtx) to [codementor.io/events/how-to-work-with-your-engineering-lead-dz0h527vtx?ref=devevents](https://codementor.io/events/how-to-work-with-your-engineering-lead-dz0h527vtx) to help us track traffic from your excellent website.

Hope you can help correct the information. Thanks lot!

**Comment by unicorncoding** [comment]
Hey,

Thanks for you email,

Both links that you have send to me below are the same

Best regards,
Julija

Вт, 8 марта 2022 г. в 16:41, RichardCYC ***@***.***>:

**Comment by RichardCYC** [comment]
Hi Julija,

Thanks for your prompt reply!

The two links are direct to the same page as you mentioned while there is a
query string on the second URL, which is ref=devevents. The query string is
for us to know the users who click the links are from https://dev.events/.
Without it, we can not know how many users are attracted from your site. It
is critical for us.

Please help correct the information when you are available and let me know
if there is anything unclear.

Thanks lot!

Richard

**Comment by RichardCYC** [comment]
Hi Julija,

I was wondering if you had helped correct the event information? Please let
me know if there is anything that I can help with.

Thanks!

Richard
