### ISSUE TITLE
UTM Link is missing from Submitted Event

### ISSUE THREAD

**Issue by Dkreiger** [unicorncoding/devevents-web#37]
Hello, 

I have submitted an event. I have noticed our Partner UTM link provided is not used on the event submission. 

https://dev.events/conferences/snowpark-day-online-3-2022

**Comment by unicorncoding** [comment]
Hi,

Yes, we're removing all trackings from the links, otherwise they look ugly :-)

**Comment by Dkreiger** [comment]
Are we able to track how many people click on our event?
