### ISSUE TITLE
<Web Directions Code 2023> <https://webdirections.org/code>

### ISSUE THREAD

**Issue by JohnAllsopp** [unicorncoding/devevents-web#419]
#Australia's conference for JavaScript Developers and Front End Engineers

##Melbourne June 2023

Progressive Web Apps (PWAs) first saw the light of day at Code 2015, when Alex Russell, their originator, outlined the then weeks old concept.

Since 2015, the Web platform has increased in sophistication, with new capabilities and APIs. Web Apps are increasingly closer to being first class citizens on platforms like Android and even iOS.

Code focusses on developing these apps, and the Web platform as a whole. We'll cover browser APIs, technologies like JavaScript and CSS, as well as patterns and best practices for developing fast, safe, secure, sophisticated web applications.

###Who's it for?
Whether you call yourself a coder, a programmer a developer or engineer, if your job is to build and deliver robust, fast, secure, engaging web experiences, Code is for you.

Code is for front end engineers: JavaScript, Fullstack and Web developers, engineering leads, engineering managers, devops experts, CTOs.

**Comment by unicorncoding** [comment]
the date is not announced

**Comment by JohnAllsopp** [comment]
added exact dates-June 26 and 27th
