### ISSUE TITLE
Please add event Scenic City Summit https://sceniccitysummit.com

### ISSUE THREAD

**Issue by stuartdga** [unicorncoding/devevents-web#423]
Scenic City Summit is a software development conference designed to cover all aspects of software development regardless of the technology stack. The conference is June 2, 2023 in Chattanooga, TN.

Date: June 2, 2023

Country: 
US

Categories:
Full Stack
Software Architecture
Frontend

I submitted this earlier and realize that I entered the wrong year (2022).

**Comment by unicorncoding** [comment]
https://dev.events/conferences/scenic-city-summit-chattanooga-5-2023
