### ISSUE TITLE
Please add event <embO++ Meeting the experts on embedded systems> <https://www.embo.io>

### ISSUE THREAD

**Issue by AItobe** [unicorncoding/devevents-web#505]
The emBO++ brings together programmers, developers and interested parties in the context of embedded systems and hardware-related software development. Together we discuss as an international community with speakers from all over the world the particular challenges that arise in this area.

**The emBO++ will be held in bochum, germany, from march 23 to 25, 2023.**
We fill 2 full days with talks on topics ranging from physics and classical electrical engineering, system design of boards for embedded systems embedded systems, development toolchains, programming libraries to special features of programming languages and their standardization.

On Thursday the 23.03.2023 the emBO++ starts with a relaxed get together in the center of Bochum. On Friday there will be lectures on an international top level from morning till evening to finish the day at the Volkswagen Infotainment Dinner. Saturday is again filled with presentations and in the evening we let it rip at the aftershow party. 

[The ticket includes food and drinks for all events](https://shop.skunkforce.org). The proceeds will go to our non-profit organization Open Skunkforce e.V..

**Comment by sizovs** [comment]
Added.
