### ISSUE TITLE
Add Masterclass: Multiplatform App Development in Kotlin

### ISSUE THREAD

**Issue by mlvandijk** [unicorncoding/devevents-web#667]
Please add the following Masterclass "Multiplatform App Development in Kotlin" by Pamela Hill at GOTO Copenhagen on October 5th, 2023.
For details: https://gotocph.com/2023/masterclasses/423/multiplatform-app-development-in-kotlin

**Comment by unicorncoding** [comment]
Will add it in the next few days. Please note there is a [Add an event] button at the bottom of the website.
