### ISSUE TITLE
React on the beach

### ISSUE THREAD

**Issue by katerinaxy** [unicorncoding/devevents-web#669]
Hi, 

there should be an event called React on the beach, happening 7th Sept, official website https://reactonthebeach.com, but it unfortunately doesn't work and I'm struggling to buy tickets. Could you help me, please? 

Katerina

**Comment by unicorncoding** [comment]
Hi @katerinaxy 

We're not organizing that conference, and their website is down, so I can't help here. But I recommend attending [DevTernity conference](https://devternity.com) because it's awesome and always works.

– Julia
