### ISSUE TITLE
DeveloperWeek Europe

### ISSUE THREAD

**Issue by savadevic** [unicorncoding/devevents-web#75]
DeveloperWeek Europe (April 27-28, 2022) connects 3,000+ engineering professionals and technical practitioners & leaders from across Europe. 

Come join us as the community gathers for two days of education, software best practices, and networking -- an all-virtual conference with 9+ tracks, a 2-day Virtual Expo, an Online Hackathon, and more.

DeveloperWeek Europe is the premier developer & software engineering event for Europe, with 3,000+ developers, engineers, software architects, dev managers, IT professionals, and technical executives gathering (online in 2022) for learning best practices & the newest trends, making connections, and uniting the global developer community.

We'll feature 9+ Conferences & Tracks covering:

-API & Microservices
-Artificial Intelligence & Machine Learning
-Blockchain & Fintech
-Containers & Kubernetes
-DevOps & Security
-JavaScript
-Cloud, Data & Digital Transformation
-New Programming Languages & Platforms
-Tech Trends Europe
-DevExec World & the DevLead Conference (for managers, team leads, VPs & CTOs)

With 2 days of cutting-edge sessions and technical workshop tracks, we cover the newest innovations in engineering best practices.

**Comment by unicorncoding** [comment]
done ✓
