### ISSUE TITLE
Online Free Frontend Meetup from Lemon.io <https://events.lemon.io/>

### ISSUE THREAD

**Issue by heygid** [unicorncoding/devevents-web#79]
**All eyes on you! Learn about the latest domain-driven Front-End principles and other hooks to keep customers' attention.**

Online Free Frontend Meetup for middle and senior European developers will take place 5th May 2022, 17:00 (UTC +3).

Meetup Better Frontend for Better Results will be held in English. There will be a lecture from keynote speaker Eliran Natan, R&D software architect at Axonius, and a panel discussion with Eliran Natan, Dávid Lévai, a content creator, indie developer, and digital nomad, Yurii Lubynets, Senior React Developer, and moderator Nazar Tokar, senior frontend developer, youtube tech/cybersec blogger. 

REGISTER HERE: https://events.lemon.io/ 

About organizer: Lemon.io - it's the Ukrainian marketplace for developers who want to find part-time or full-time project in Europe.

**Comment by unicorncoding** [comment]
done ✓

**Comment by heygid** [comment]
@unicorncoding hello! thanks for quick reply. does it mean that our event is visible now on the dev.event site?

**Comment by unicorncoding** [comment]
yes, it is ) https://dev.events/conferences/frontend-meetup-from-lemon-io-online-4-2022

**Comment by heygid** [comment]
I see, great, thank you! Could we add something to this preview? https://prnt.sc/P7lFygjhngGQ
and I don't see our meetup in the list of conferences https://prnt.sc/rpgn5rDZMpu_ would you please add also? :)

**Comment by unicorncoding** [comment]
"Could we add something to this preview?" - no, we can't
"I don't see our meetup in the list of conferences" - check out a little later, it will appear
