### ISSUE TITLE
<Global DevSlam 2022> <https://globaldevslam.com/>

### ISSUE THREAD

**Issue by gitex2022** [unicorncoding/devevents-web#82]
Global DevSlam 2022 presented by GITEX Global is the worlds largest developer and tech skill building event; bringing together a collation of 8000 coders, developers, programmers, data scientists, DevOps Professionals and software engineers scientists from over 30 countries
 
With 4 days of conferences, work shops, learning labs, certified training programs and hackathons, no matter where you are in your career you will be surrounded by opportunities to learn, debate and innovate whilst forging alliances and building connections
 
Make sure that you are part of pioneering the future and join the unique, rapidly expanding ecosystem with more than 150 fortune 500  enterprises, innovative governments and cutting edge startups 

•	Event Dates: 10 October to 14 October 2022
•	Venue: Dubai World Trade Centre, Dubai, United Arab Emirates

**Comment by unicorncoding** [comment]
Hey, thank you for sharing your event. Quick question before I add it to the listing. Is it paid or free event?

**Comment by gitex2022** [comment]
Dear Git Hub team

This is a free event

Please find the summary below:


Global DevSlam 2022 presented by GITEX Global is the worlds largest developer and tech skill building event; bringing together a collation of 8000 coders, developers, programmers, data scientists, DevOps Professionals and software engineers scientists from over 30 countries.



With 4 days of conferences, work shops, learning labs, certified training programs and hackathons, no matter where you are in your career you will be surrounded by opportunities to learn, debate and innovate whilst forging alliances and building connections.



Make sure that you are part of pioneering the future and join the unique, rapidly expanding ecosystem with more than 150 fortune 500  enterprises, innovative governments and cutting edge startups.



  *   Event Dates: 10 October to 14 October 2022
  *   Venue: Dubai World Trade Centre, Dubai, United Arab Emirates
  *   More Info: https://www.gitex.com/globaldevslam


Regards,
Mahanaz

__________________________________________________
Mahanaz Tarapore
Marketing Manager
Events Management Business Support
Dubai World Trade Centre
.........................................................................................................................................................................................
P.O.Box: , Dubai, United Arab Emirates | | | | www.dwtc.com<http://www.dwtc.com>
