### ISSUE TITLE
<TechBash> <https://techbash.com/>

### ISSUE THREAD

**Issue by annabateman** [unicorncoding/devevents-web#85]
At TechBash we inspire our attendees to build great things that will change the world. The sessions at TechBash will deliver bleeding edge advances in the coding, designing and development of mobile, web, desktop and SaaS applications. Our speakers are world class knowledge experts you may have seen featured at other conferences like DevIntersections, NDC, VS Live (Visual Studio Live), and Google I/O. We keep adding an inclusive variety of speakers to the list, so check back regularly to see who’s up next.

**Comment by unicorncoding** [comment]
https://dev.events/conferences/tech-bash-pocono-manor-10-2022
