### ISSUE TITLE
<SKILup Festival: Denver><https://www.skilupfestival.io/denver-22>

### ISSUE THREAD

**Issue by CJeffers-10** [unicorncoding/devevents-web#89]
This is not your typical conference, this is a Live DevOps Educational Experience. This 2 day in-person event is designed with IT professionals in mind, offering a platform to network, connect and foster continuous learning opportunities in a one-of-a-kind festival environment.

**Comment by unicorncoding** [comment]
https://dev.events/conferences/ski-lup-festival-denver-5-2022
