### ISSUE TITLE
Please add event <Tech Summit> <https://techsummit.tech/>

### ISSUE THREAD

**Issue by AllTechEvents** [unicorncoding/devevents-web#98]
Two days of incredible masterclasses, workshops, speakers, tech leaders, leading tech brands, networking, opportunities, recruiters and more. This is set to be an unmissable event for anyone in Tech.

Professional Development

Developer Sessions, Masterclasses and more

Skills Development

Emerging Technologies

Networking

Date: June 28-29th 2022

Event Times:
Day 1: Tuesday 28th June 2022: 8.30AM - 5.00PM

Day 2: Wednesday 28th June 2022: 8.30AM - 3.10PM

Location: Marriott Marquis, 780 Mission Street, San Francisco, California 94103 USA

**Comment by unicorncoding** [comment]
https://dev.events/conferences/tech-summit-san-francisco-5-2022
